batch_size: 1
checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /tmp/Meta-Llama-3-8B-Instruct/original/
  checkpoint_files: [consolidated.00.pth]
  model_type: LLAMA3
  output_dir: /tmp/Meta-Llama-3-8B-Instruct/
  recipe_checkpoint: null
dataset: {_component_: torchtune.datasets.hellaswag_dataset}
device: cuda
dtype: bf16
enable_activation_checkpointing: true
epochs: 1
gradient_accumulation_steps: 1
log_every_n_steps: 1
log_peak_memory_stats: false
loss: {_component_: torch.nn.CrossEntropyLoss}
lr_scheduler: {_component_: torchtune.modules.get_cosine_schedule_with_warmup, num_warmup_steps: 100}
max_steps_per_epoch: 200
metric_logger: {_component_: torchtune.utils.metric_logging.DiskLogger, log_dir: '${output_dir}'}
model:
  _component_: torchtune.models.llama3.async_lora_llama3_8b
  apply_lora_to_mlp: true
  apply_lora_to_output: true
  bsz: 1
  gpus_per_config: 2
  lora_alpha: [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
  lora_attn_modules: [q_proj, k_proj, v_proj, output_proj, gate_proj, up_proj, down_proj]
  lora_rank: [32, 32, 32, 32, 32, 128, 128, 128, 128, 128, 128, 128, 128]
optimizer: {_component_: torch.optim.AdamW, lr: 3e-4, weight_decay: 0.01}
output_dir: /tmp/lora_finetune_output
resume_from_checkpoint: false
seed: null
shuffle: true
tokenizer: {_component_: torchtune.models.llama3.llama3_tokenizer, path: /tmp/Meta-Llama-3-8B-Instruct/original/tokenizer.model}
